# Generated by Django 2.2.6 on 2019-12-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('file', models.ImageField(upload_to='partners')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cordination', models.CharField(choices=[('DAC', 'DAC'), ('DAECC', 'DAECC'), ('DSP', 'DSP'), ('Msamala ASP', 'Msamala ASP'), ('Nkaya ASP', 'Nkaya ASP'), ('Kachenga ASP', 'Kachenga ASP'), ('Chanthunya ASP', 'Chanthunya ASP'), ('Kalembo ASP', 'Kalembo ASP'), ('Amidu ASP', 'Amidu ASP'), ('Sawali ASP', 'Sawali ASP'), ('Matola ASP', 'Matola ASP'), ('Phalula ASP', 'Phalula ASP'), ('Toleza ASP', 'Toleza ASP')], default='DAECC', max_length=100)),
                ('specify', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('Orgnisation', models.CharField(blank=True, max_length=100)),
                ('desination', models.CharField(blank=True, max_length=100)),
                ('phone', models.PositiveIntegerField(blank=True, default=0)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('file', models.ImageField(upload_to='Team')),
            ],
        ),
    ]
