# Generated by Django 2.2.6 on 2019-12-26 07:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('docu', models.FileField(upload_to='Files')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('asp', models.CharField(blank=True, choices=[('Msamala', 'Msamala'), ('Nkaya', 'Nkaya'), ('Kachenga', 'Kachenga'), ('Chanthunya', 'Chanthunya'), ('Kalembo', 'Kalembo'), ('Amidu', 'Amidu'), ('Sawali', 'Sawali'), ('Matola', 'Matola'), ('Phalula', 'Phalula'), ('Toleza', 'Toleza')], max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('Event_date', models.DateField()),
                ('time', models.TimeField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='events')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daess_item', to='event.events')),
            ],
        ),
    ]
