# Generated by Django 2.2.6 on 2019-12-26 07:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cordination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asp', models.CharField(max_length=100)),
                ('male', models.PositiveIntegerField(blank=True, null=True)),
                ('female', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('vac_no', models.PositiveIntegerField(blank=True, null=True)),
                ('vac_name', models.CharField(blank=True, max_length=100)),
                ('discription', ckeditor.fields.RichTextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Agricuture Extension video', 'Agricuture Extension video'), ('Nutrition Extension videos', 'Nutrition Extension videos'), ('Documentary', 'Documentary'), ('Success stories', 'Success stories'), ('Event', 'Event')], default='Extension video', max_length=100)),
                ('location', models.CharField(blank=True, choices=[('Msamala', 'Msamala'), ('Nkaya', 'Nkaya'), ('Kachenga', 'Kachenga'), ('Chanthunya', 'Chanthunya'), ('Kalembo', 'Kalembo'), ('Amidu', 'Amidu'), ('Sawali', 'Sawali'), ('Matola', 'Matola'), ('Phalula', 'Phalula'), ('Toleza', 'Toleza')], max_length=100)),
                ('video', models.URLField()),
            ],
        ),
    ]
