# Generated by Django 2.2.6 on 2019-12-26 07:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('NGO', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, choices=[('Msamala', 'Msamala'), ('Nkaya', 'Nkaya'), ('Kachenga', 'Kachenga'), ('Chanthunya', 'Chanthunya'), ('Kalembo', 'Kalembo'), ('Amidu', 'Amidu'), ('Sawali', 'Sawali'), ('Matola', 'Matola'), ('Phalula', 'Phalula'), ('Toleza', 'Toleza'), ('Mpilisi', 'Mpilisi'), ('Ulongwe', 'Ulongwe'), ('Rivirivi', 'Rivirivi'), ('Utale', 'Utale')], max_length=200)),
                ('areas', models.CharField(blank=True, max_length=200)),
                ('PJ_link', models.URLField(blank=True)),
                ('body', ckeditor.fields.RichTextField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('docu', models.FileField(blank=True, upload_to='pj file')),
                ('image', models.ImageField(upload_to='projects')),
            ],
        ),
        migrations.CreateModel(
            name='item_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daess_item', to='project.Projects')),
            ],
        ),
    ]
