# Generated by Django 2.2.6 on 2019-12-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
