# Generated by Django 2.2.6 on 2019-12-26 07:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orginisaton', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('Commission Based', 'Commission Based'), ('Consultancy', 'Consultancy'), ('Contract', 'Contract'), ('Event', 'Event'), ('Full Time', 'Full Time'), ('Funding', 'Funding'), ('Hourly Paid', 'Hourly Paid'), ('International', 'International'), ('Internship', 'Internship'), ('Part Time', 'Part Time'), ('Scholarship', 'Scholarship'), ('Seasonal', 'Seasonal'), ('Short-Term', 'Short-Term'), ('Temporary', 'Temporary'), ('Training', 'Training'), ('Volunteer', 'Volunteer')], max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, null=True)),
                ('closing_date', models.DateField()),
                ('body', ckeditor.fields.RichTextField()),
                ('view', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(blank=True, upload_to='logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daess_item', to='career.job')),
            ],
        ),
    ]
