# Generated by Django 2.2.6 on 2019-12-26 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Banana', 'Banana'), ('Beans', 'Beans'), ('Cereals', 'Cereals'), ('Chemicals', 'Chemicals'), ('Fruits', 'Fruits'), ('Garri', 'Garri'), ('Livestock', 'Livestock'), ('Melon', 'Melon'), ('Oil Nature', 'Oil Nature'), ('Pawpaw', 'Pawpaw'), ('Plantain', 'Plantain'), ('Seeds', 'Seeds'), ('Tomatoes', 'Tomatoes'), ('Tractors', 'Tractors'), ('Tubers', 'Tubers'), ('Vegetables', 'Vegetables'), ('Yam', 'Yam')], max_length=300)),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_com', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(choices=[('Msamala', 'Msamala'), ('Nkaya', 'Nkaya'), ('Kachenga', 'Kachenga'), ('Chanthunya', 'Chanthunya'), ('Kalembo', 'Kalembo'), ('Amidu', 'Amidu'), ('Sawali', 'Sawali'), ('Matola', 'Matola'), ('Phalula', 'Phalula'), ('Toleza', 'Toleza')], default='Matola', max_length=30)),
                ('stock', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, choices=[('Smallholder', 'Smallholder'), ('Cooperative', 'Cooperative'), ('Agro dealers', 'Agro dealers'), ('Others', 'Others')], max_length=600, null=True)),
                ('specify', models.CharField(blank=True, max_length=40)),
                ('real_name', models.CharField(blank=True, max_length=600, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('view', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Dicription', models.TextField(blank=True, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='Products')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daess_item', to='products.products')),
            ],
        ),
    ]
